# nixpacks.toml
[phases.setup]
nixPkgs = ["...", "nodejs"] # Ensures PHP and Node are installed

[phases.build]
cmds = [
    "composer install --no-dev --optimize-autoloader",
    "npm install",
    "npm run build",
    "rm -f public/hot"
]

[start]
cmd = "php artisan config:cache && php artisan route:cache && php artisan view:cache && php artisan migrate --force && php artisan serve --host 0.0.0.0 --port $PORT"
